const en = "EN-US";
const de = "DE-DE";
const fr = "FR-FR";
const ru = "RU-RU";
const pl = "PL-PL";
const es = "ES-ES";
const pt = "PT-BR";
const zh = "ZH-CN";
const ko = "KO-KR";

const Translate = {
  title: {
    [en]: "Albion Online Tool",
    [de]: "Albion Online Werkzeug",
    [fr]: "Albion Online Outil",
    [ru]: "Albion Online Инструмент",
    [pl]: "Albion Online Narzędzie",
    [es]: "Albion Online Instrumento",
    [pt]: "Albion Online ferramenta",
    [zh]: "Albion Online 工具",
    [ko]: "Albion Online 수단",
  },
  market: {
    [en]: "Market",
    [de]: "Markt",
    [fr]: "Marché",
    [ru]: "рынок",
    [pl]: "Rynek",
    [es]: "Mercado",
    [pt]: "Mercado",
    [zh]: "市场",
    [ko]: "시장",
  },
  guilds: {
    [en]: "Guilds",
    [de]: "Gilden",
    [fr]: "Guildes",
    [ru]: "гильдий",
    [pl]: "Gildie",
    [es]: "Gremios",
    [pt]: "Guildas",
    [zh]: "公会",
    [ko]: "길드",
  },
  players: {
    [en]: "Players",
    [de]: "Spieler",
    [fr]: "Joueurs",
    [ru]: "игроки",
    [pl]: "Gracze",
    [es]: "Jugadores",
    [pt]: "Jogadoras",
    [zh]: "玩家们",
    [ko]: "선수",
  },
  guild: {
    [en]: "Guild",
    [de]: "Gilde",
    [fr]: "Guilde",
    [ru]: "Гильдия",
    [pl]: "Gildia",
    [es]: "Gremio",
    [pt]: "Guilda",
    [zh]: "公会",
    [ko]: "동업 조합",
  },
  player: {
    [en]: "Players",
    [de]: "Spieler",
    [fr]: "Joueurs",
    [ru]: "игроки",
    [pl]: "Gracze",
    [es]: "Jugadores",
    [pt]: "Jogadoras",
    [zh]: "玩家们",
    [ko]: "선수",
  },
  settings: {
    [en]: "Settings",
    [de]: "Einstellungen",
    [fr]: "Paramètres",
    [ru]: "настройки",
    [pl]: "Ustawienia",
    [es]: "Configuraciones",
    [pt]: "Configurações",
    [zh]: "设定值",
    [ko]: "설정",
  },
  back: {
    [en]: "Back",
    [de]: "Zurück",
    [fr]: "Retourner",
    [ru]: "назад",
    [pl]: "Wróć",
    [es]: "Regresa",
    [pt]: "Volte",
    [zh]: "回去",
    [ko]: "돌",
  },
  search: {
    [en]: "Search",
    [de]: "Suche",
    [fr]: "Chercher",
    [ru]: "Поиск",
    [pl]: "Szukaj",
    [es]: "Buscar",
    [pt]: "Procurar",
    [zh]: "搜索",
    [ko]: "검색",
  },
  enterItem: {
    [en]: "Enter an Item Name",
    [de]: "Geben Sie einen Artikelnamen ein",
    [fr]: "Entrez un nom d'article",
    [ru]: "Введите название предмета",
    [pl]: "Wprowadź nazwę elementu",
    [es]: "Ingrese un Nombre de Artículo",
    [pt]: "Digite o Nome do Item",
    [zh]: "输入项目名称",
    [ko]: "품목 이름을 입력하십시오",
  },
  enterGuild: {
    [en]: "Enter a Guild Name",
    [de]: "Gib einen Gildennamen ein",
    [fr]: "Entrez un nom de guilde",
    [ru]: "Введите название гильдии",
    [pl]: "Wpisz nazwę gildii",
    [es]: "Ingrese un Nombre de Gremio",
    [pt]: "Digite um Nome de Guilda",
    [zh]: "输入公会名称",
    [ko]: "길드 이름을 입력하세요",
  },
  enterPlayer: {
    [en]: "Enter a Player Name",
    [de]: "Geben Sie einen Spielernamen ein",
    [fr]: "Entrez un nom de joueur",
    [ru]: "Введите имя игрока",
    [pl]: "Wpisz nazwę gracza",
    [es]: "Ingrese un Nombre de Jugador",
    [pt]: "Digite o Nome de um Jogador",
    [zh]: "输入玩家名称",
    [ko]: "플레이어 이름을 입력하십시오",
  },
  submit: {
    [en]: "Submit",
    [de]: "Einreichen",
    [fr]: "Soumettre",
    [ru]: "Отправить",
    [pl]: "Zatwierdź",
    [es]: "Enviar",
    [pt]: "Enviar",
    [zh]: "提交",
    [ko]: "제출",
  },
  bPrice: {
    [en]: "Buy Price",
    [de]: "Kaufpreis",
    [fr]: "Acheter Prix",
    [ru]: "Купить Цена",
    [pl]: "Kup cenę",
    [es]: "Precio de Compra",
    [pt]: "Preço de Compra",
    [zh]: "购买价格",
    [ko]: "구매 가격",
  },
  sPrice: {
    [en]: "Sell Price",
    [de]: "Verkaufspreis",
    [fr]: "Prix de Vente",
    [ru]: "Цена продажи",
    [pl]: "Cena sprzedaży",
    [es]: "Precio de Venta",
    [pt]: "Preço de Venda",
    [zh]: "销售价格",
    [ko]: "판매 가격",
  },
  quality: {
    [en]: "Quality",
    [de]: "Qualität",
    [fr]: "Qualité",
    [ru]: "Качество",
    [pl]: "Jakości",
    [es]: "Calidad",
    [pt]: "Quality",
    [zh]: "质量",
    [ko]: "품질",
  },
  normal: {
    [en]: "Normal",
    [de]: "Normalen",
    [fr]: "Normal",
    [ru]: "Нормальной",
    [pl]: "Normalne",
    [es]: "Normal",
    [pt]: "Normal",
    [zh]: "正常",
    [ko]: "정상적인",
  },
  good: {
    [en]: "Good",
    [de]: "Gut",
    [fr]: "Bon",
    [ru]: "Хорошо",
    [pl]: "Dobry",
    [es]: "Bien",
    [pt]: "Bom",
    [zh]: "好",
    [ko]: "좋은",
  },
  outstanding: {
    [en]: "Outstanding",
    [de]: "Hervorragend",
    [fr]: "Exceptionnelle",
    [ru]: "Выдающиеся",
    [pl]: "Wybitne",
    [es]: "Outstanding",
    [pt]: "Excelente",
    [zh]: "优秀",
    [ko]: "뛰어난",
  },
  excellent: {
    [en]: "Excellent",
    [de]: "Ausgezeichnet",
    [fr]: "Excellente",
    [ru]: "Отлично",
    [pl]: "Doskonałe",
    [es]: "Excelente",
    [pt]: "Excelente",
    [zh]: "非常好",
    [ko]: "훌륭한",
  },
  masterpiece: {
    [en]: "Masterpiece",
    [de]: "Meisterwerk",
    [fr]: "Chef-d'œuvre",
    [ru]: "Шедевр",
    [pl]: "Arcydzieło",
    [es]: "Obra maestra",
    [pt]: "Obra prima",
    [zh]: "杰作",
    [ko]: "걸작",
  },
  relatedG: {
    [en]: "Related Guilds",
    [de]: "Verwandte Gilden",
    [fr]: "Guildes connexes",
    [ru]: "Родственные гильдии",
    [pl]: "Powiązane gildie",
    [es]: "Gremios relacionados",
    [pt]: "Guildas Relacionadas",
    [zh]: "相关公会",
    [ko]: "관련 길드",
  },
  allianceT: {
    [en]: "Alliance Tag",
    [de]: "Allianz-Tag",
    [fr]: "Étiquette d’alliance",
    [ru]: "Тег Альянса",
    [pl]: "Tag sojuszu",
    [es]: "Etiqueta de la Alianza",
    [pt]: "Tag aliança",
    [zh]: "联盟标签",
    [ko]: "얼라이언스 태그",
  },
  founder: {
    [en]: "Founder",
    [de]: "Gründer",
    [fr]: "Fondateur",
    [ru]: "Основатель",
    [pl]: "Założyciel",
    [es]: "Fundador",
    [pt]: "Fundador",
    [zh]: "创始人",
    [ko]: "설립자",
  },
  memberC: {
    [en]: "Member Count",
    [de]: "Mitgliederanzahl",
    [fr]: "Nombre de Membres",
    [ru]: "Подсчет членов",
    [pl]: "Liczba członków",
    [es]: "Recuento de Miembros",
    [pt]: "Contagem de Membros",
    [zh]: "成员计数",
    [ko]: "멤버 수",
  },
  members: {
    [en]: "Members",
    [de]: "Mitglieder",
    [fr]: "Membres",
    [ru]: "Членов",
    [pl]: "Członków",
    [es]: "Miembros",
    [pt]: "Membros",
    [zh]: "成员",
    [ko]: "멤버",
  },
  associate: {
    [en]: "Associate of",
    [de]: "Assoziierter von",
    [fr]: "Associé de",
    [ru]: "Ассоциированный из",
    [pl]: "Współpracownik",
    [es]: "Asociado de",
    [pt]: "Associado de",
    [zh]: "关联",
    [ko]: "연결",
  },
  combatStats: {
    [en]: "Combat Stats",
    [de]: "Kampfstatistiken",
    [fr]: "Statistiques de combat",
    [ru]: "Боевая статистика",
    [pl]: "Statystyki bojowe",
    [es]: "Estadísticas de combate",
    [pt]: "Estatísticas de Combate",
    [zh]: "战斗统计",
    [ko]: "전투 통계",
  },
  kFame: {
    [en]: "Kill Fame",
    [de]: "Ruhm töten",
    [fr]: "tuer la célébrité",
    [ru]: "Убить славу",
    [pl]: "Zabij sławę",
    [es]: "Matar fama",
    [pt]: "Matar a Fama",
    [zh]: "杀死名声",
    [ko]: "명예 를 죽여",
  },
  dFame: {
    [en]: "Death Fame",
    [de]: "Todesruhm",
    [fr]: "La renommée de la mort",
    [ru]: "Слава смерти",
    [pl]: "Sława śmierci",
    [es]: "Fama de Muerte",
    [pt]: "Fama da Morte",
    [zh]: "死亡名声",
    [ko]: "죽음의 명성",
  },
  fameRatio: {
    [en]: "Fame Ratio",
    [de]: "Ruhmesverhältnis",
    [fr]: "Ratio de renommée",
    [ru]: "Коэффициент славы",
    [pl]: "Współczynnik sławy",
    [es]: "Relación de fama",
    [pt]: "Proporção de Fama",
    [zh]: "名望比",
    [ko]: "명예 비율",
  },
  pveStats: {
    [en]: "PVE Stats",
    [de]: "PVE-Statistiken",
    [fr]: "Statistiques PVE",
    [ru]: "PVE Статистика",
    [pl]: "Statystyki PVE",
    [es]: "Estadísticas de PVE",
    [pt]: "Estatísticas do PVE",
    [zh]: "PVE 统计数据",
    [ko]: "PVE 통계",
  },
  royalFame: {
    [en]: "Royal Fame",
    [de]: "Königlicher Ruhm",
    [fr]: "Renommée royale",
    [ru]: "Королевская слава",
    [pl]: "Królewska sława",
    [es]: "Fama Real",
    [pt]: "Fama Real",
    [zh]: "皇家名人",
    [ko]: "로얄 페임",
  },
  outlandsFame: {
    [en]: "Outlands Fame",
    [de]: "Ruhm im Ausland",
    [fr]: "Renommée hors des terres",
    [ru]: "Запредельная слава",
    [pl]: "Sława Rubieży",
    [es]: "Fama de las Tierras Exteriores",
    [pt]: "Fama no exterior",
    [zh]: "外陆名人",
    [ko]: "아웃랜드 명예",
  },
  hellgateFame: {
    [en]: "HellGate Fame",
    [de]: "HellGate Ruhm",
    [fr]: "Renommée HellGate",
    [ru]: "АдГейт славы",
    [pl]: "HellGate Fame",
    [es]: "Fama de HellGate",
    [pt]: "Fama do Portão do Inferno",
    [zh]: "地狱门名人",
    [ko]: "헬게이트 명예",
  },
  tFame: {
    [en]: "Total Fame",
    [de]: "Totaler Ruhm",
    [fr]: "Renommée totale",
    [ru]: "Полная слава",
    [pl]: "Całkowita sława",
    [es]: "Total Fama",
    [pt]: "Fama Total",
    [zh]: "总名次",
    [ko]: "총 명성",
  },
  language: {
    [en]: "Language",
    [de]: "Sprache",
    [fr]: "Langue",
    [ru]: "Язык",
    [pl]: "Język",
    [es]: "Idioma",
    [pt]: "Idioma",
    [zh]: "语言",
    [ko]: "언어",
  },
};
/*
  word: {
    [en]: "",
    [de]: "",
    [fr]: "",
    [ru]: "",
    [pl]: "",
    [es]: "",
    [pt]: "",
    [zh]: "",
    [ko]: "",
  },
*/

export default Translate;
